name: Release dataset to staging or production DB

on:
  workflow_dispatch:
    inputs: 
      megaset-name:
        description: "Enter the name of the megaset to release every dataset within"
        type: string
        default: ""
      dataset-id: 
        description: "Enter the ID in the format [NAME]_v[VERSION] to release a single dataset"
        type: string
        default: ""
      database:
        description: "Please choose a database to release dataset"
        type: choice
        default: "staging"
        options: 
        - staging
        - production

env:
  NODE_ENV: ${{ github.event.inputs.database }}
  STAGING_FIREBASE_TOKEN: ${{ secrets.STAGING_FIREBASE_TOKEN }}
  STAGING_FIREBASE_EMAIL: ${{ secrets.STAGING_FIREBASE_EMAIL }}
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  FIREBASE_EMAIL: ${{ secrets.FIREBASE_EMAIL }}
  AWS_SECRET: ${{ secrets.CFE_AWS_SECRET }}
  AWS_ID: ${{ secrets.CFE_AWS_ID }}
  ADMINS: ${{ secrets.OWNERS }}


jobs:     
  release_dataset: 
    name: Release Dataset
    runs-on: ubuntu-latest
    if:  github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - name: Release dataset
        if: contains(env.ADMINS, github.triggering_actor)
        run: |
          npm run release-dataset ${{ github.event.inputs.megaset-name }} ${{ github.event.inputs.dataset-id }}
          echo "${{ github.event.inputs.megaset-name }} ${{ github.event.inputs.dataset-id }} is successfully released to ${{ github.event.inputs.database }} database."
      - name: Not authorized to release dataset
        if: ${{ !contains(env.ADMINS, github.triggering_actor) }}
        run: echo "Failed to release dataset. Please contact the owner of the repository to obtain the permission."
  get_admins:
    runs-on: ubuntu-latest
    steps:
      - name: Get collaborators
        run: |
          curl --request GET \
          --header "Accept: application/vnd.github+json" \
          --header "X-GitHub-Api-Version: 2022-11-28" \
          --url https://api.github.com/repos/${{ github.repository }}/contributors \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
