name: Release dataset to production DB

on:
  workflow_dispatch:
    inputs: 
      megaset-name:
        description: "Enter the name of the megaset to release every dataset within"
        type: string
        default: ""
      dataset-id: 
        description: "Enter the ID in the format [NAME]_v[VERSION] to release a single dataset"
        type: string
        default: ""
      database:
        description: "Please choose a database to release dataset"
        type: choice
        default: "staging"
        options: 
        - staging
        - production

env:
      NODE_ENV: ${{ github.event.inputs.database }}
      STAGING_FIREBASE_TOKEN: ${{ secrets.STAGING_FIREBASE_TOKEN }}
      STAGING_FIREBASE_EMAIL: ${{ secrets.STAGING_FIREBASE_EMAIL }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      FIREBASE_EMAIL: ${{ secrets.FIREBASE_EMAIL }}
      AWS_SECRET: ${{ secrets.CFE_AWS_SECRET }}
      AWS_ID: ${{ secrets.CFE_AWS_ID }}
      ADMINS: '["meganrm", "toloudis"]' #${{ secrets.OWNERS }}


jobs:
  # check_user:
  #   name: Authorization Check
  #   runs-on: ubuntu-latest
  #   outputs:
  #     admins: ${{ steps.check.outputs.admins }}
  #   steps: 
  #     - name: Env variable ADMINS to output
  #       id: check
  #       run: | 
  #         echo "admins=${{ env.ADMINS }}" >> $GITHUB_OUTPUT
  #         echo "${{ steps.check.outputs.admins }}" 
        
  release_dataset: 
    name: Release Dataset
    runs-on: ubuntu-latest
    # needs: [check_user]
    # if:  github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      # - run: npm ci
      - name: Release dataset
        if: contains(env.ADMINS, github.triggering_actor)
      #   run: npm run release-dataset ${{ github.event.inputs.megaset-name }} ${{ github.event.inputs.dataset-id }}
        run: echo "would run"
      - name: specify database 
        run: echo "${{ github.event.inputs.megaset-name }} ${{ github.event.inputs.dataset-id }} is successfully released to ${{ github.event.inputs.database }} database."
      - name: debug
        run: |
          echo "${{ github.triggering_actor }}"
          echo "${{ github.ref }}"
          echo "${{ env.ADMINS }}"