name: Upload dataset to staging or production DB

on:
  workflow_dispatch:
    inputs: 
      dataset-folder:
        description: "Enter the relative path to the new dataset"
        required: true
      skip-per-cell-upload:
        type: boolean
        description: "Set to true to skip the file-info upload (save some processing time)"
        default: false
      database:
        description: "Please choose a database to release dataset"
        type: choice
        default: "staging"
        options: 
        - staging
        - production

env:
  NODE_ENV: ${{ github.event.inputs.database }}
  STAGING_FIREBASE_TOKEN: ${{ secrets.STAGING_FIREBASE_TOKEN }}
  STAGING_FIREBASE_EMAIL: ${{ secrets.STAGING_FIREBASE_EMAIL }}
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  FIREBASE_EMAIL: ${{ secrets.FIREBASE_EMAIL }}
  AWS_SECRET: ${{ secrets.CFE_AWS_SECRET }}
  AWS_ID: ${{ secrets.CFE_AWS_ID }}
  ADMINS: ${{ secrets.OWNERS }}

jobs: 
  process_dataset_to_staging: 
    name: Process Dataset to Stag
    runs-on: ubuntu-latest
    if: github.event.inputs.database == 'staging'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - name: Process dataset to staging
        run: echo "${{ github.event.inputs.database }}"
        # run: npm run process-dataset ${{ github.event.inputs.dataset-folder }} ${{ github.event.inputs.skip-per-cell-upload}}

  process_dataset_to_production: 
    name: Process Dataset to Prod
    runs-on: ubuntu-latest
    if: github.event.inputs.database == 'production' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - name: Process dataset to production
        if: contains(env.ADMINS, github.triggering_actor)
        run: echo "${{ github.event.inputs.database }}"
        # run: npm run process-dataset ${{ github.event.inputs.dataset-folder }} ${{ github.event.inputs.skip-per-cell-upload}}
      - name: Not authorized to process dataset to production
        if: ${{ !contains(env.ADMINS, github.triggering_actor) }}
        run: echo "Failed to process dataset to production database. Please contact the owner of the repository to obtain the permission."
      - name: debug
        run: | 
          echo "${{ github.ref }}"
          echo "${{ github.triggering_actor }}"

